import test from 'node:test';
import assert from 'node:assert/strict';
import {recordEquipmentUse,equipmentAttention,equipmentReadiness,replacementCost,youthGearDisposition} from '../src/systems/equipmentConsumables.js';
import {normalizeSupportAsset,applySupportToExpense,exclusivityConflict,endSupportContract,supportedProgramFeasibility} from '../src/systems/equipmentSupport.js';

test('consumables deplete and affect readiness',()=>{let f={id:'f1',category:'filter',quantity:1,condition:100};f=recordEquipmentUse(f,{sessions:1,kind:'race',conditions:{mud:true}});assert.equal(f.quantity,0);assert.equal(equipmentAttention(f).urgent,true);assert.equal(equipmentReadiness([f]).ready,false);});
test('worn safety gear triggers stronger replacement than apparel',()=>{const boots=equipmentAttention({id:'b',category:'boots',condition:58});const jersey=equipmentAttention({id:'j',category:'jersey',condition:35});assert.equal(boots.urgent,true);assert.equal(jersey.urgent,false);});
test('helmet replacement is safety critical',()=>{const h=equipmentAttention({id:'h',category:'helmet',condition:60});assert.equal(h.replace,true);assert.equal(h.reason,'safety-wear');});
test('outgrown youth gear creates hand-me-down/market decision',()=>{const d=youthGearDisposition({id:'g',category:'boots',fitStatus:'outgrown',retailPrice:250},{marketValue:80,siblingCanUse:true});assert.equal(d.needed,true);assert.ok(d.options.some(x=>x.id==='hand-me-down'));assert.ok(d.options.some(x=>x.id==='sell'&&x.value===80));});
test('sponsor-supported gear reduces real out of pocket expense',()=>{assert.deepEqual(replacementCost({category:'gloves',retailPrice:40},{allotmentRemaining:1}).outOfPocket,0);const x=applySupportToExpense({category:'gear',amount:500},[{id:'s',gearDiscountPct:40,gearCredit:100}]);assert.equal(x.outOfPocket,200);assert.equal(x.support,300);});
test('ownership source and return obligations are explicit',()=>{const a=normalizeSupportAsset({assetId:'bike1',ownershipSource:'team-owned'},{contractId:'c1'});assert.equal(a.returnRequired,true);const ended=endSupportContract([a],'c1');assert.equal(ended[0].action,'return');assert.equal(ended[0].asset.ownershipStatus,'return-due');});
test('dealer discount and product support can make a multi-bike program feasible',()=>{const f=supportedProgramFeasibility({annualBikeCost:9000,annualPartsCost:3000,annualGearCost:1500,availableCash:9000,packages:[{id:'dealer',bikeDiscountPct:25,partsDiscountPct:30},{id:'sponsor',gearDiscountPct:100,bikeLoans:[{assetId:'practice'}]}]});assert.equal(f.affordable,true);assert.equal(f.supportsMultiBike,true);});
test('unsupported privateer carries full burden',()=>{const f=supportedProgramFeasibility({annualBikeCost:7000,annualPartsCost:2000,annualGearCost:1000,availableCash:6000,packages:[]});assert.equal(f.totalSupport,0);assert.equal(f.affordable,false);});
test('exclusivity detects conflicting product use',()=>{const c=exclusivityConflict({category:'gear',brand:'BrandB'},[{id:'s',provider:'BrandA',exclusivity:[{category:'gear',brand:'BrandA'}]}]);assert.equal(c.conflict,true);});
