import test from 'node:test';
import assert from 'node:assert/strict';
import { Game } from '../src/game.js';
import { familyStory, initializeFamilyBuilder, ensureFamilyBuilderInitialized, migrateLegacyFamilyBuilder } from '../src/systems/familyBuilderExperience.js';

test('Your Story reflects selected dimensions without inventing a permanent archetype',()=>{const story=familyStory({financial:'tight',motocrossKnowledge:'industry',household:'single_parent',school:'public'},{supportModel:'guardian_mechanic',home:'basic'},{age:11});assert.match(story.title,/Tight-budget/);assert.match(story.title,/industry-connected/);assert.match(story.subtitle,/Public school/);assert.match(story.subtitle,/Single-parent household/);assert.ok(story.pressures.includes('money'));assert.ok(story.strengths.includes('motocross knowledge'));assert.deepEqual(story.riderPerformanceModifiers,{});});

test('contrasting family builds create different life constraints but identical rider skills',()=>{const a=new Game({riderName:'A',seed:11,background:null});const b=new Game({riderName:'B',seed:12,background:null});const skillsA={...a.state.rider.skills};const skillsB={...b.state.rider.skills};initializeFamilyBuilder(a,{financial:'tight',motocrossKnowledge:'industry',household:'single_parent',school:'public'},{supportModel:'family_diy',home:'minimal'});initializeFamilyBuilder(b,{financial:'wealthy',motocrossKnowledge:'new',household:'two_parent',school:'homeschool'},{supportModel:'professional',home:'rural'});assert.equal(a.state.familyBuilder.initialized,true);assert.equal(b.state.familyBuilder.initialized,true);assert.ok(a.state.family.money<b.state.family.money);assert.notEqual(a.state.familyLife.school.travelFlex,b.state.familyLife.school.travelFlex);assert.notEqual(a.state.familyLife.home.property.storageCapacity,b.state.familyLife.home.property.storageCapacity);assert.deepEqual(a.state.rider.skills,skillsA);assert.deepEqual(b.state.rider.skills,skillsB);});

test('initialization is idempotent and does not duplicate family actors or money',()=>{const g=new Game({seed:22,background:null});initializeFamilyBuilder(g,{financial:'comfortable',motocrossKnowledge:'weekend',household:'two_parent',school:'public'},{supportModel:'guardian_mechanic',home:'basic'});const cash=g.state.family.money;const actorIds=Object.keys(g.state.relationships);const opening=g.state.careerEconomy.openingBalance;initializeFamilyBuilder(g,{financial:'wealthy',motocrossKnowledge:'industry',household:'single_parent',school:'rural'},{supportModel:'professional',home:'rural'});assert.equal(g.state.family.money,cash);assert.equal(g.state.careerEconomy.openingBalance,opening);assert.deepEqual(Object.keys(g.state.relationships),actorIds);});

test('legacy background migration maps dimensions while preserving active career money',()=>{const g=new Game({seed:33,background:null});g.state.background='working_class';g.state.family.money=4321;g.state.careerEconomy={version:2,openingBalance:1200,ledger:[{id:'earned',sourceId:'earned',amount:-3121}],seenSourceIds:['earned'],reconciliations:[]};delete g.state.familyBuilder;migrateLegacyFamilyBuilder(g.state);assert.equal(g.state.familyBuilder.builder.financial,'tight');ensureFamilyBuilderInitialized(g);assert.equal(g.state.family.money,4321);assert.equal(g.state.careerEconomy.ledger.length,1);assert.equal(g.state.familyBuilder.initialized,true);});

test('save/load preserves Family Builder selections and canonical life state',()=>{const g=new Game({riderName:'Save Rider',seed:44,background:null});initializeFamilyBuilder(g,{financial:'well_off',motocrossKnowledge:'motocross_family',household:'split_household',school:'online'},{supportModel:'hybrid',home:'workshop'});const save=structuredClone(g.toSave());const loaded=Game.load(save);ensureFamilyBuilderInitialized(loaded);assert.equal(loaded.state.familyBuilder.builder.financial,'well_off');assert.equal(loaded.state.familyBuilder.builder.school,'online');assert.equal(loaded.state.familyBuilder.support.home,'workshop');assert.equal(loaded.state.familyLife.home.homeId,'workshop');assert.equal(loaded.state.familyLife.support.model,'hybrid');assert.ok(Object.keys(loaded.state.relationships).includes('parent-1'));assert.deepEqual(loaded.state.familyLife.home.riderPerformanceModifiers,{});});
