import test from 'node:test';
import assert from 'node:assert/strict';
import {createRacingSupportHomeState,resolveRacingSupport,raceWeekendSupportAttribution,startingHomeCircumstances,familySupportHomeSummary} from '../src/systems/familyRacingSupportHome.js';

test('guardian mechanic support attributes race-weekend work to the configured person',()=>{const builder={household:'two_parent',motocrossKnowledge:'motocross_family',guardians:[{id:'mom',name:'Mom',relation:'Parent',roles:{wrenches:true,attendsRaces:true,financialSupport:true}},{id:'dad',name:'Dad',relation:'Parent',roles:{travelSchool:true,emotionalSupport:true}}]};const resolved=resolveRacingSupport(builder,{supportModel:'guardian_mechanic'});const attribution=raceWeekendSupportAttribution(builder,{supportModel:'guardian_mechanic'});assert.equal(resolved.primaryProviderId,'mom');assert.equal(attribution.mechanicId,'mom');assert.equal(attribution.payerId,'mom');assert.deepEqual(resolved.riderPerformanceModifiers,{});});

test('local shop creates a recurring dealer relationship and costs more family cash but less labor',()=>{const builder={motocrossKnowledge:'weekend'};const shop=resolveRacingSupport(builder,{supportModel:'local_shop'});const diy=resolveRacingSupport(builder,{supportModel:'family_diy'});assert.equal(shop.primaryProviderId,'support-local-shop');assert.equal(shop.people.find(p=>p.id==='support-local-shop')?.lifecycle?.role,'Dealer');assert.ok(shop.economy.supportCostPressure>diy.economy.supportCostPressure);assert.ok(shop.life.familyTimeLoad<diy.life.familyTimeLoad);});

test('professional help raises maintenance capacity without changing rider talent',()=>{const pro=resolveRacingSupport({motocrossKnowledge:'new'},{supportModel:'professional'});const diy=resolveRacingSupport({motocrossKnowledge:'new'},{supportModel:'family_diy'});assert.ok(pro.garageSupport.maintenanceCapacity>diy.garageSupport.maintenanceCapacity);assert.deepEqual(pro.riderPerformanceModifiers,{});});

test('minimal home creates real storage and service constraints',()=>{const home=startingHomeCircumstances({financial:'tight',motocrossKnowledge:'new'},{home:'minimal',supportModel:'family_diy'});assert.equal(home.equipment.storageConstraint,'severe');assert.ok(home.property.transportConstraint>=70);assert.ok(home.garage.maintenanceCapacity<50);assert.equal(home.compoundSeed.ridingSpaceEligibility,false);assert.deepEqual(home.riderPerformanceModifiers,{});});

test('rural property provides room to expand but has meaningful upkeep pressure',()=>{const rural=startingHomeCircumstances({financial:'comfortable',motocrossKnowledge:'weekend'},{home:'rural',supportModel:'guardian_mechanic'});const basic=startingHomeCircumstances({financial:'comfortable',motocrossKnowledge:'weekend'},{home:'basic',supportModel:'guardian_mechanic'});assert.ok(rural.property.ridingSpace>basic.property.ridingSpace);assert.ok(rural.property.expandability>basic.property.expandability);assert.ok(rural.economy.propertyUpkeepPressure>basic.economy.propertyUpkeepPressure);assert.equal(rural.compoundSeed.ridingSpaceEligibility,true);});

test('home choice does not override family finances or guarantee new equipment',()=>{const wealthyMinimal=startingHomeCircumstances({financial:'wealthy'},{home:'minimal'});const tightWorkshop=startingHomeCircumstances({financial:'tight'},{home:'workshop'});assert.equal(wealthyMinimal.equipment.startingPosture,'premium-capable');assert.equal(tightWorkshop.equipment.startingPosture,'used-budget');assert.equal(tightWorkshop.equipment.newBikeExpectation,false);assert.ok(tightWorkshop.garage.toolLevel>wealthyMinimal.garage.toolLevel);});

test('summary exposes strengths and pressures instead of a difficulty class',()=>{const story=familySupportHomeSummary({financial:'tight',motocrossKnowledge:'industry'},{home:'rural',supportModel:'family_diy'});assert.ok(story.pressures.includes('property upkeep'));assert.ok(story.pressures.includes('family time'));assert.ok(story.strengths.includes('space to ride'));assert.ok(story.strengths.includes('strong tool setup'));});

test('support state accepts explicit custom race-role assignment',()=>{const state=createRacingSupportHomeState({supportModel:'hybrid',assignments:{wrenching:'mom',transport:'dad',registration:'mom',schoolCoordination:'dad',financialSupport:'mom'}});assert.equal(state.assignments.wrenching,'mom');assert.equal(state.assignments.transport,'dad');});
