import test from 'node:test';
import assert from 'node:assert/strict';
import {createFamilyLifeBuilderState,startingCircumstances,householdTemplate,ensureHouseholdActors,schoolWeekConstraints,changeSchoolStructure,familyBuilderSummary} from '../src/systems/familyLifeBuilder.js';

test('wealth and motocross knowledge are independent dimensions',()=>{const wealthyNew=startingCircumstances({financial:'wealthy',motocrossKnowledge:'new'});const tightIndustry=startingCircumstances({financial:'tight',motocrossKnowledge:'industry'});assert.ok(wealthyNew.economy.startingCash>tightIndustry.economy.startingCash);assert.ok(tightIndustry.motocross.advicePrecision>wealthyNew.motocross.advicePrecision);assert.ok(tightIndustry.motocross.networkExposure>wealthyNew.motocross.networkExposure);assert.deepEqual(wealthyNew.riderPerformanceModifiers,{});assert.deepEqual(tightIndustry.riderPerformanceModifiers,{});});

test('household templates generate persistent People 2.0 actors',()=>{const builder=createFamilyLifeBuilderState({household:'split_household'});const template=householdTemplate(builder.household);assert.equal(template.length,2);const people=ensureHouseholdActors(builder);assert.equal(people.length,2);assert.equal(people[0].id,'parent-1');assert.ok(people[0].lifecycle);assert.equal(people[0].familyBuilder.guardian.relation,'Parent');});

test('guardian roles are customizable without gender assumptions',()=>{const people=ensureHouseholdActors({household:'two_parent',guardians:[{id:'mom',name:'Mom',relation:'Parent',motocrossKnowledge:'industry',roles:{wrenches:true,attendsRaces:true,financialSupport:true}},{id:'dad',name:'Dad',relation:'Parent',motocrossKnowledge:'new',roles:{travelSchool:true,emotionalSupport:true}}]});assert.equal(people[0].familyBuilder.guardian.roles.wrenches,true);assert.equal(people[0].familyBuilder.guardian.motocrossKnowledge,'industry');assert.equal(people[1].familyBuilder.guardian.motocrossKnowledge,'new');});

test('school structures create different calendar pressure without speed modifiers',()=>{const publicWeek=schoolWeekConstraints({school:'public'},{age:12,raceTravelDays:3});const homeWeek=schoolWeekConstraints({school:'homeschool'},{age:12,raceTravelDays:3});assert.ok(publicWeek.absencePressure>homeWeek.absencePressure);assert.ok(homeWeek.travelFlex>publicWeek.travelFlex);assert.ok(publicWeek.schoolworkLoad>0);const publicState=startingCircumstances({school:'public'});const homeState=startingCircumstances({school:'homeschool'});assert.deepEqual(publicState.riderPerformanceModifiers,{});assert.deepEqual(homeState.riderPerformanceModifiers,{});});

test('school structure can evolve and records history',()=>{let builder=createFamilyLifeBuilderState({school:'public'});builder=changeSchoolStructure(builder,'online',{seasonNumber:4,week:2,reason:'national-travel'});assert.equal(builder.school,'online');assert.equal(builder.history.length,1);assert.equal(builder.history[0].from,'public');assert.equal(builder.history[0].to,'online');});

test('family summary combines circumstances instead of inventing an archetype',()=>{const summary=familyBuilderSummary({financial:'tight',motocrossKnowledge:'motocross_family',household:'single_parent',school:'public'});assert.equal(summary.financial,'Tight');assert.equal(summary.motocross,'Motocross family');assert.equal(summary.household,'single_parent');assert.equal(summary.school,'Public school');assert.ok(summary.pressures.includes('money'));assert.ok(summary.strengths.includes('mechanical knowledge'));});
