import test from 'node:test';
import assert from 'node:assert/strict';
import { ensureRecurringBond,recordBondInteraction,bondOpportunity,recordBondIntroduction,evolveRecurringRole,rivalryProfile,financialPosture,evaluateCommitment } from '../src/systems/peopleEconomyBondsRisk.js';
import { ensureRelationshipLifecycle } from '../src/systems/peopleRelationships2.js';

test('rivalry can build respect and friendship without erasing competition',()=>{let rival=ensureRecurringBond({id:'rival-1',role:'Rival',values:{rivalry:65,friendship:55,respect:60,trust:55}});rival=recordBondInteraction(rival,{kind:'race_battle',clean:true,intensity:4,seasonNumber:2,week:5,raceWeek:true});rival=recordBondInteraction(rival,{kind:'conversation',intensity:3,seasonNumber:2,week:6});const p=rivalryProfile(rival);assert.ok(p.respect>=60);assert.ok(p.friendship>=50);assert.ok(p.rivalry>0);assert.equal(rival.lifecycle.bond.encounters,2);});

test('mechanic and mentor history can originate specific introductions',()=>{let mechanic=ensureRecurringBond({id:'mike',role:'Mechanic',values:{trust:80,respect:75,loyalty:80,friendship:65}});mechanic=recordBondInteraction(mechanic,{kind:'wrench',intensity:4,seasonNumber:3,week:2});mechanic=recordBondInteraction(mechanic,{kind:'wrench',intensity:3,seasonNumber:3,week:4});const op=bondOpportunity(mechanic,{seasonNumber:3,week:5});assert.equal(op.eligible,true);assert.equal(op.actorId,'mike');assert.equal(op.kind,'mechanic-network');mechanic=recordBondIntroduction(mechanic,op);assert.equal(mechanic.lifecycle.bond.introductions.length,1);});

test('role evolution preserves relationship and bond history',()=>{let coach=ensureRecurringBond({id:'coach',role:'Coach',values:{trust:75,respect:80}});coach=recordBondInteraction(coach,{kind:'coaching',intensity:3,seasonNumber:2,week:3});coach=evolveRecurringRole(coach,'Mentor',{seasonNumber:4,week:1});assert.equal(coach.lifecycle.role,'Mentor');assert.equal(coach.lifecycle.roleHistory.length,1);assert.equal(coach.lifecycle.bond.encounters,1);});

test('financial posture distinguishes stable program from debt and thin-cushion pressure',()=>{const stable=financialPosture(null,{cash:12000,plannedCost:5000,monthlyLivingCost:1200,debtExposure:0,archetype:'supported_amateur',equipmentRisk:10});const strained=financialPosture(null,{cash:900,plannedCost:9000,monthlyLivingCost:1600,debtExposure:7000,archetype:'national_privateer',equipmentRisk:75,familyStrain:65});assert.equal(stable.band,'stable');assert.ok(['strained','critical'].includes(strained.band));assert.ok(strained.pressureScore>stable.pressureScore+30);assert.ok(strained.drivers.length);});

test('risk posture changes viable commitments but never rider speed',()=>{const posture=financialPosture(null,{cash:1800,plannedCost:7000,monthlyLivingCost:1200,debtExposure:3000,archetype:'regional_privateer'});const decision=evaluateCommitment(posture,{cost:1400,reserveRequired:700,risk:70});assert.equal(decision.allowed,false);assert.ok(decision.reason);assert.equal('speed' in posture,false);});

test('legacy relationship still normalizes before becoming a recurring bond',()=>{const legacy=ensureRelationshipLifecycle({id:'dealer',role:'Dealer',values:{trust:70,support:65}});const bond=ensureRecurringBond(legacy);assert.equal(bond.lifecycle.bond.role,'Dealer');assert.ok(Number.isFinite(bond.lifecycle.dimensions.trust));});
