import { test, expect } from '@playwright/test';
async function noOverflow(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);}

test('People and Economy 2.0 tell the relationship and funding story on mobile',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.waitForFunction(()=>!!window.__legacy);
 await page.evaluate(async()=>{localStorage.clear();const a=window.__legacy;a.startGame({name:'Story Rider',depth:'detailed',birthdate:'2012-05-15',campaign:'parent',avatar:'🧒',background:'working_class'});const rel=await import(new URL('src/systems/peopleEconomyLifePressure.js',document.baseURI).href);const integ=await import(new URL('src/systems/peopleEconomyIntegration.js',document.baseURI).href);a.game.state.relationships.dad=rel.createConflict(a.game.state.relationships.dad,{source:'money',severity:2,seasonNumber:1,week:3});integ.attributePersonSupport(a.game,{actorId:'dad',sourceId:'dad-trip',kind:'travel-and-wrenching',money:250,time:8,labor:5,context:'Regional weekend'});integ.payCareerExpense(a.game,700,{sourceId:'race-cost',category:'race-weekend',description:'Regional weekend',funding:[{source:'team',amount:450,type:'team-paid'}]});a.game.state.financialPosture={monthlyLivingCost:1000,debtExposure:1200,equipmentRisk:35,familyStrain:40,archetype:'family_youth'};a.tab='stats';a.render();});
 const people=page.getByTestId('people-relationship-story'),economy=page.getByTestId('career-economy-story');await expect(people).toBeVisible();await expect(economy).toBeVisible();await expect(people).toContainText('Needs attention');await expect(people).toContainText('$250');await expect(economy).toContainText('OUT OF POCKET');await expect(economy).toContainText('SUPPORT COVERED');await expect(economy).toContainText('$450');await noOverflow(page);
 await people.getByRole('button',{name:'Apology'}).click();expect(await page.evaluate(()=>window.__legacy.game.state.relationships.dad.lifecycle.activeConflict.repairProgress)).toBeGreaterThan(0);await noOverflow(page);
 await page.setViewportSize({width:1280,height:900});await noOverflow(page);
});
