export const CAREER_OPPORTUNITY_VERSION=2;
const clamp=(v,lo=0,hi=100)=>Math.max(lo,Math.min(hi,Number(v)||0));
const nowKey=(ctx)=>`s${ctx.seasonNumber??1}:w${ctx.week??0}`;
const id=(type,source,ctx)=>`${type}:${source}:${nowKey(ctx)}`;
export function createCareerOpportunityState(raw={}){return{version:2,active:[...(raw.active??[])],history:[...(raw.history??[])],relationships:{...(raw.relationships??{})},team:raw.team??null,manufacturer:raw.manufacturer??null,media:[...(raw.media??[])],mentors:[...(raw.mentors??[])],mobility:{...(raw.mobility??{})},contract:raw.contract??null};}
function metrics(ctx){const r=ctx.rider??{},f=ctx.family??{},results=ctx.results??{};return{age:Number(r.age??12),klass:r.klass??ctx.klass??'unknown',form:clamp(ctx.form??results.form??results.score??50),reputation:clamp(ctx.reputation??50),professionalism:clamp(ctx.professionalism??60),visibility:clamp(ctx.visibility??35),money:Number(f.money??ctx.money??0),support:clamp(ctx.support??(Number(f.support_level??0)*20)),relationship:clamp(ctx.relationship??50),readiness:clamp(ctx.readiness??60),development:clamp(ctx.development??60),injury:!!r.injury,region:ctx.region??'home',momentum:clamp(ctx.momentum??50)};}
function offer(type,source,ctx,p={}){const m=metrics(ctx);const score=clamp(p.score??(m.form*.28+m.reputation*.18+m.professionalism*.14+m.relationship*.12+m.readiness*.16+m.momentum*.12));return{id:id(type,source,ctx),version:2,type,source,title:p.title??type,createdAt:nowKey(ctx),expiresWeek:Number(ctx.week??0)+(p.expiresIn??3),eligibility:{score,minimum:p.minimum??50,eligible:score>=(p.minimum??50),reasons:p.reasons??[]},fit:clamp(p.fit??score),value:clamp(p.value??score),risk:clamp(p.risk??35),terms:p.terms??{},obligations:p.obligations??[],familyImpact:p.familyImpact??{},opportunityCost:p.opportunityCost??[],guardianRequired:m.age<18,status:'offered',scope:p.scope??null};}
export function discoverCareerOpportunities(raw,ctx={}){const state=createCareerOpportunityState(raw),m=metrics(ctx),c=[];
 if(m.form>=58||m.reputation>=60)c.push(offer('team-seat',m.region==='home'?'local-shop-team':'regional-team',ctx,{title:m.form>=78?'Regional Team Seat':'Shop Team Support Ride',minimum:55,value:72,risk:32,terms:{equipmentSupport:m.form>=75?70:40,travelSupport:m.form>=70?50:20,term:'season'},obligations:['team branding','selected races','professional conduct'],familyImpact:{travel:m.form>=70?'moderate':'low'}}));
 if(m.form>=68&&m.professionalism>=58)c.push(offer('manufacturer','manufacturer-amateur',ctx,{title:'Manufacturer Amateur Support',minimum:62,value:82,risk:28,terms:{bikeDiscount:35,partsCredit:1200,technicalSupport:true,preferredDealer:true},obligations:['brand exclusivity','product use','contingency events']}));
 if(m.development<72||m.readiness<70)c.push(offer('training','regional-coach',ctx,{title:'Invite-Only Development Camp',minimum:45,value:65,risk:18,terms:{cost:325,days:3,developmentFocus:'weaknesses'},familyImpact:{school:'3 days',travel:'moderate'},obligations:['attendance','coach plan']}));
 if(m.visibility>=50||m.form>=72)c.push(offer('media','regional-media',ctx,{title:'Regional Rider Feature',minimum:50,value:58,risk:22,terms:{visibilityGain:10},obligations:['interview','sponsor compliance']}));
 if(m.form>=72&&m.region==='home')c.push(offer('mobility','southeast-program',ctx,{title:'Winter Southeast Development Block',minimum:62,value:76,risk:48,terms:{kind:'seasonal-travel',weeks:6,cost:2800},familyImpact:{school:'high',work:'high',supportNetwork:'reduced'},opportunityCost:['home series rounds']}));
 if(m.readiness>=64)c.push(offer('class-move','next-class',ctx,{title:'Consider Moving Up a Class',minimum:55,value:64,risk:42,terms:{timing:'strategic',newBikeRequired:true},opportunityCost:['current-class championship','adaptation reset']}));
 if(ctx.rosterGap&&m.form>=60)c.push(offer('fill-in','replacement-seat',ctx,{title:'Short-Notice Replacement Ride',minimum:58,value:88,risk:55,expiresIn:1,terms:{rounds:ctx.fillInRounds??2,temporary:true,equipmentProvided:true},obligations:['team schedule','brand compliance']}));
 if((ctx.contractFocus??null))c.push(offer('contract-scope','selective-program',ctx,{title:'Selective Series Contract',minimum:50,value:68,risk:34,terms:{focus:ctx.contractFocus,rounds:ctx.rounds??'selected',testing:true},scope:{series:ctx.contractFocus,rounds:ctx.rounds??'selected'}}));
 const seen=new Set([...state.active,...state.history].map(x=>`${x.type}:${x.source}:${x.status}`));
 for(const o of c)if(o.eligibility.eligible&&!seen.has(`${o.type}:${o.source}:accepted`)&&!state.active.some(x=>x.type===o.type&&x.source===o.source&&x.status==='offered'))state.active.push(o);
 return state;}
export function evaluateOpportunity(stateRaw,opportunityId,ctx={}){const state=createCareerOpportunityState(stateRaw),o=state.active.find(x=>x.id===opportunityId);if(!o)return null;const m=metrics(ctx);const affordability=Number(o.terms?.cost??0)<=m.money;const familyReady=!o.guardianRequired||ctx.guardianApproved===true||m.support>=55;return{opportunity:o,affordable:affordability,familyReady,upside:o.value,risk:o.risk,recommendation:!affordability?'decline-or-negotiate':!familyReady?'family-review':o.value-o.risk>=25?'accept':'consider'};}
export function decideCareerOpportunity(stateRaw,opportunityId,decision,ctx={}){const state=createCareerOpportunityState(stateRaw),i=state.active.findIndex(x=>x.id===opportunityId);if(i<0)return{state,error:'not-found'};const o={...state.active[i]};if(o.guardianRequired&&decision==='accept'&&ctx.guardianApproved!==true)return{state,error:'guardian-approval-required'};if(decision==='counter'){o.status='countered';o.counter={requestedAt:nowKey(ctx),terms:{...o.terms,...(ctx.counterTerms??{})}};state.history.push(o);state.active.splice(i,1);return{state,opportunity:o};}o.status=decision==='accept'?'accepted':'declined';o.decidedAt=nowKey(ctx);state.history.push(o);state.active.splice(i,1);if(o.status==='accepted')applyAccepted(state,o,ctx);return{state,opportunity:o};}
function applyAccepted(state,o,ctx){if(o.type==='team-seat'||o.type==='fill-in')state.team={source:o.source,title:o.title,terms:o.terms,scope:o.scope??null};if(o.type==='manufacturer')state.manufacturer={source:o.source,terms:o.terms};if(o.type==='training')state.mentors.push({source:o.source,startedAt:nowKey(ctx),quality:o.value});if(o.type==='media')state.media.push({source:o.source,at:nowKey(ctx),visibility:Number(o.terms?.visibilityGain??0)});if(o.type==='mobility')state.mobility={source:o.source,...o.terms};if(o.type==='contract-scope')state.contract={source:o.source,...o.terms,scope:o.scope};if(o.type==='class-move')state.pendingClassMove={source:o.source,...o.terms};}
export function expireCareerOpportunities(stateRaw,week){const state=createCareerOpportunityState(stateRaw);const keep=[];for(const o of state.active){if(Number(o.expiresWeek)<Number(week)){state.history.push({...o,status:'expired'});}else keep.push(o);}state.active=keep;return state;}
export function aiChooseOpportunity(opportunity,ai={}){const ambition=clamp(ai.ambition??60),stability=clamp(ai.stability??50),money=Number(ai.money??5000);const disruption=opportunity.type==='fill-in'?1:opportunity.type==='mobility'?1.2:opportunity.familyImpact?.travel==='high'?1:.35;let score=opportunity.value-opportunity.risk*.62+(ambition-50)*.38-(stability-50)*.28*disruption;if(Number(opportunity.terms?.cost??0)>money)score-=35;if(opportunity.type==='fill-in'&&ambition<40)score-=12;return score>=40?'accept':score>=27?'counter':'decline';}
export function careerOpportunitySummary(stateRaw){const s=createCareerOpportunityState(stateRaw);return{active:s.active.length,accepted:s.history.filter(x=>x.status==='accepted').length,declined:s.history.filter(x=>x.status==='declined').length,expired:s.history.filter(x=>x.status==='expired').length,currentTeam:s.team?.title??null,currentManufacturer:s.manufacturer?.source??null,currentContract:s.contract??null,recent:s.history.slice(-5).reverse()};}
