export const CAREER_ECONOMY_VERSION=2;
export const CASH_KINDS=new Set(['income','expense','sale-proceeds','race-earnings','work-income','household-funding','refund']);

const amount=(v)=>Math.max(0,Math.round(Number(v)||0));
export function createCareerEconomyState(raw={},openingBalance=0){const source=raw&&typeof raw==='object'?raw:{};return{version:2,openingBalance:Number(source.openingBalance??openingBalance),ledger:[...(source.ledger??[])],seenSourceIds:[...(source.seenSourceIds??[])],reconciliations:[...(source.reconciliations??[])]};}
function sourceKey(entry,state){return String(entry.sourceId??`${entry.kind??'entry'}:${entry.seasonNumber??1}:${entry.week??0}:${state.ledger.length}`);}
export function recordEconomicEntry(raw,entry={},openingBalance=0){const state=createCareerEconomyState(raw,openingBalance);const sourceId=sourceKey(entry,state);const duplicate=state.seenSourceIds.includes(sourceId);if(duplicate)return{state,entry:state.ledger.find(x=>x.sourceId===sourceId)??null,duplicate:true};
 const cashDelta=Math.round(Number(entry.cashDelta??0));const row={id:`econ:${sourceId}`,sourceId,seasonNumber:Number(entry.seasonNumber??1),week:Number(entry.week??0),kind:entry.kind??(cashDelta<0?'expense':'income'),category:entry.category??'uncategorized',description:entry.description??null,cashDelta,fundingSource:entry.fundingSource??(cashDelta<0?'family':'unknown'),beneficiary:entry.beneficiary??'rider',expenseOwner:entry.expenseOwner??(cashDelta<0?'family':null),supportType:entry.supportType??null,designated:entry.designated??null,nonCashValue:amount(entry.nonCashValue),personId:entry.personId??null,linkedSupportId:entry.linkedSupportId??null};state.ledger.push(row);state.seenSourceIds.push(sourceId);return{state,entry:row,duplicate:false};}

export function recordCashChange(raw,delta,meta={},openingBalance=0){return recordEconomicEntry(raw,{...meta,cashDelta:Math.round(Number(delta)||0),kind:meta.kind??(delta<0?'expense':'income')},openingBalance);}

export function recordFundedExpense(raw,{sourceId,seasonNumber=1,week=0,category='racing',description=null,gross=0,funding=[],beneficiary='rider'}={},openingBalance=0){
 const state0=createCareerEconomyState(raw,openingBalance);if(state0.seenSourceIds.includes(String(sourceId)))return{state:state0,duplicate:true,expense:null};
 const grossAmount=amount(gross);const normalized=(funding??[]).map(x=>({source:x.source??'family',amount:amount(x.amount),type:x.type??(x.source==='family'?'cash':'support'),personId:x.personId??null}));let covered=normalized.reduce((a,b)=>a+b.amount,0);if(covered<grossAmount)normalized.push({source:'family',amount:grossAmount-covered,type:'cash',personId:null});covered=normalized.reduce((a,b)=>a+b.amount,0);const familyCash=normalized.filter(x=>['family','rider'].includes(x.source)&&x.type==='cash').reduce((a,b)=>a+b.amount,0);const support=normalized.filter(x=>!(['family','rider'].includes(x.source)&&x.type==='cash')).reduce((a,b)=>a+b.amount,0);
 const result=recordEconomicEntry(state0,{sourceId,seasonNumber,week,kind:'expense',category,description,cashDelta:-familyCash,fundingSource:normalized.length===1?normalized[0].source:'split',beneficiary,expenseOwner:'race-program',supportType:support?'mixed-support':null,designated:{gross:grossAmount,outOfPocket:familyCash,support,shares:normalized},nonCashValue:support},openingBalance);
 return{...result,duplicate:false,expense:{gross:grossAmount,outOfPocket:familyCash,support,shares:normalized}};
}

export function economySummary(raw,{seasonNumber=null}={}){const s=createCareerEconomyState(raw);const rows=seasonNumber==null?s.ledger:s.ledger.filter(x=>x.seasonNumber===Number(seasonNumber));const cashIn=rows.filter(x=>x.cashDelta>0).reduce((a,b)=>a+b.cashDelta,0),cashOut=-rows.filter(x=>x.cashDelta<0).reduce((a,b)=>a+b.cashDelta,0),support=rows.reduce((a,b)=>a+Number(b.designated?.support??b.nonCashValue??0),0);const byCategory={};const bySource={};for(const r of rows){byCategory[r.category]=(byCategory[r.category]??0)+Math.abs(r.cashDelta);bySource[r.fundingSource]=(bySource[r.fundingSource]??0)+Math.abs(r.cashDelta)+Number(r.designated?.support??0);}return{entries:rows.length,cashIn,cashOut,netCash:cashIn-cashOut,support,byCategory,bySource};}
export function expectedBalance(raw){const s=createCareerEconomyState(raw);return s.openingBalance+s.ledger.reduce((a,b)=>a+b.cashDelta,0);}
export function reconcileEconomy(raw,actualBalance,meta={}){const s=createCareerEconomyState(raw),expected=expectedBalance(s),difference=Math.round(Number(actualBalance)||0)-expected;const row={seasonNumber:Number(meta.seasonNumber??1),week:Number(meta.week??0),actualBalance:Math.round(Number(actualBalance)||0),expectedBalance:expected,difference,ok:difference===0};s.reconciliations.push(row);return{state:s,...row};}
