import { migrateBikeOwnership, setBikeRole } from './equipmentOwnership.js';
import { recordBikeUsage, performService } from './equipmentWear.js';
import { createMarketplaceState, createPlayerListing, completePrivateSale, dealerTradeIn } from './equipmentMarketplace.js';
import { inspectUsedListing, purchaseUsedBike } from './usedEquipmentBuying.js';
import { recordEquipmentUse, replacementCost } from './equipmentConsumables.js';
import { applySupportToExpense } from './equipmentSupport.js';

function clone(v){return JSON.parse(JSON.stringify(v));}
export function createEquipmentCareerState(raw={}){
 return {version:2,ownership:migrateBikeOwnership(raw.ownership??raw),market:createMarketplaceState(raw.market),gear:Array.isArray(raw.gear)?clone(raw.gear):[],cash:Math.round(Number(raw.cash)||0),ledger:Array.isArray(raw.ledger)?clone(raw.ledger):[],season:Number(raw.season)||1,history:Array.isArray(raw.history)?clone(raw.history):[]};
}
function post(s,type,amount,meta={}){s.cash+=amount;s.ledger.push({type,amount,season:s.season,...meta});return s;}
export function useBike(stateRaw,bikeId,usage){const s=createEquipmentCareerState(stateRaw),i=s.ownership.bikes.findIndex(b=>b.assetId===bikeId);if(i<0)throw new Error('asset-not-owned');s.ownership.bikes[i]=recordBikeUsage(s.ownership.bikes[i],usage);s.history.push({type:'bike-use',bikeId,usage:{...usage}});return s;}
export function serviceBike(stateRaw,bikeId,service){const s=createEquipmentCareerState(stateRaw),i=s.ownership.bikes.findIndex(b=>b.assetId===bikeId);if(i<0)throw new Error('asset-not-owned');const cost=Math.max(0,Number(service.cost)||0);if(cost>s.cash)throw new Error('insufficient-cash');s.ownership.bikes[i]=performService(s.ownership.bikes[i],service);post(s,'service',-cost,{bikeId,kind:service.kind});return s;}
export function consumeGear(stateRaw,itemId,usage){const s=createEquipmentCareerState(stateRaw),i=s.gear.findIndex(g=>g.id===itemId);if(i<0)throw new Error('gear-not-owned');s.gear[i]=recordEquipmentUse(s.gear[i],usage);return s;}
export function replaceGear(stateRaw,itemId,{packages=[],retailPrice=null}={}){const s=createEquipmentCareerState(stateRaw),i=s.gear.findIndex(g=>g.id===itemId);if(i<0)throw new Error('gear-not-owned');const quote=replacementCost(s.gear[i],{retailPrice});const supported=applySupportToExpense({category:'gear',amount:quote.gross},packages);if(supported.outOfPocket>s.cash)throw new Error('insufficient-cash');post(s,'gear-replacement',-supported.outOfPocket,{itemId,support:supported.support});s.gear[i]={...s.gear[i],condition:100,uses:0,quantity:Math.max(1,s.gear[i].quantity||1),source:supported.support?'supported':'family-paid'};return s;}
export function listBikeForSale(stateRaw,bikeId,{askingPrice=null,restrictions={}}={}){const s=createEquipmentCareerState(stateRaw),bike=s.ownership.bikes.find(b=>b.assetId===bikeId);if(!bike)throw new Error('asset-not-owned');const r=createPlayerListing(s.market,bike,{askingPrice,restrictions});s.market=r.market;s.ownership=setBikeRole(s.ownership,bikeId,'for-sale');s.history.push({type:'listing-created',bikeId,listingId:r.listing.listingId});return {state:s,listing:r.listing};}
export function completeBikeSale(stateRaw,listingId,{buyer='private-buyer',price=null,provenance=null}={}){const s=createEquipmentCareerState(stateRaw),r=completePrivateSale({market:s.market,ownership:s.ownership,listingId,buyer,price,provenance,cash:s.cash});s.market=r.market;s.ownership=r.ownership;const delta=r.cash-s.cash;post(s,'equipment-sale',delta,{assetId:r.soldAsset.assetId,buyer});return s;}
export function tradeBike(stateRaw,bikeId,{context={},dealer='dealer'}={}){const s=createEquipmentCareerState(stateRaw),r=dealerTradeIn({ownership:s.ownership,bikeId,cash:s.cash,context,dealer});s.ownership=r.ownership;post(s,'trade-in',r.tradeInValue,{bikeId,dealer});return s;}
export function buyUsedBike(stateRaw,listing,{inspectionLevel='none',packages=[]}={}){const s=createEquipmentCareerState(stateRaw),support=applySupportToExpense({category:'bike',amount:listing.price},packages);if(support.outOfPocket>s.cash)throw new Error('insufficient-cash');const adjusted={...listing,price:support.outOfPocket};const purchase=purchaseUsedBike({ownership:s.ownership,listing:adjusted,cash:s.cash,inspectionLevel,compatible:listing.compatible!==false});s.cash=purchase.cash;s.ownership=purchase.ownership;const bike=s.ownership.bikes.find(b=>b.assetId===purchase.bike.assetId);if(bike&&s.ownership.bikes.filter(b=>b.role==='race').length>1)bike.role='practice';s.ledger.push({type:'used-purchase',amount:-purchase.totalCost,support:support.support,assetId:purchase.bike.assetId,season:s.season});return s;}
export function nextEquipmentSeason(stateRaw){const s=createEquipmentCareerState(stateRaw);s.season+=1;s.history.push({type:'season-rollover',season:s.season});return s;}
export function equipmentSaveRoundTrip(stateRaw){return createEquipmentCareerState(JSON.parse(JSON.stringify(createEquipmentCareerState(stateRaw))));}
export function assertEquipmentIntegrity(stateRaw){const s=createEquipmentCareerState(stateRaw),ids=s.ownership.bikes.map(b=>b.assetId),unique=new Set(ids),errors=[];if(unique.size!==ids.length)errors.push('duplicate-bike');if(!Number.isFinite(s.cash))errors.push('cash');for(const id of Object.values(s.ownership.active??{}))if(id&&!unique.has(id))errors.push('dangling-active-bike');return {valid:errors.length===0,errors,state:s};}
