import { restoreLifeBetweenRacesState, openBetweenRacesPeriod, buildOffWeekDecisionSet, resolveTrainingDecision, resolveRecoveryDecision } from './lifeBetweenRaces.js';
import { buildTrainingCatalog, quoteTrainingSession, trainingUsage, createTrainingReceipt } from './trainingPractice.js';
import { restoreTrainingAccessState, applyTrainingAccessToQuote, bookTrainingSession, consumeTrainingBooking } from './trainingAccess.js';
import { recordEquipmentUse } from './equipmentConsumables.js';

export function lifeBetweenRacesContextFromGame(game){const nextRace=(game.state.calendar??[]).find(c=>c.week>game.week&&c.race),tc=game.state.trainingContext??{},support=game.state.supportInfrastructure??{};return{week:game.week,seasonNumber:game.state.seasonNumber,isRaceWeek:game.isRaceWeek(),nextRaceWeek:nextRace?.week??null,availableSlots:game.weekSlots().length,rider:game.rider,family:game.family,bike:game.trainBike?.()??game.bike,schoolMode:game.state.schoolMode,weatherBlocked:Boolean(tc.weatherBlocked),facilityAvailable:tc.facilityAvailable??true,coachingQuality:Number(tc.coachingQuality??support.coachingQuality??50),facilityQuality:Number(tc.facilityQuality??support.trainingQuality??50)};}
export function ensureLifeBetweenRaces(game){game.state.lifeBetweenRaces=restoreLifeBetweenRacesState(game.state.lifeBetweenRaces);game.state.lifeBetweenRaces.trainingAccess=restoreTrainingAccessState(game.state.lifeBetweenRaces.trainingAccess);return game.state.lifeBetweenRaces;}
export function openLifeBetweenRaces(game){const opened=openBetweenRacesPeriod(ensureLifeBetweenRaces(game),lifeBetweenRacesContextFromGame(game));game.state.lifeBetweenRaces=opened.state;game.state.lifeBetweenRaces.trainingAccess=restoreTrainingAccessState(game.state.lifeBetweenRaces.trainingAccess);return opened;}
function supportedQuote(game,id){const base=quoteTrainingSession(game.state.lifeBetweenRaces,id,lifeBetweenRacesContextFromGame(game));return applyTrainingAccessToQuote(base,game.state.lifeBetweenRaces.trainingAccess,{seasonNumber:game.state.seasonNumber,supportDiscount:Number(game.state.trainingSupport?.discount??0),supportSource:game.state.trainingSupport?.source??null});}
export function availableLifeBetweenRacesChoices(game){openLifeBetweenRaces(game);return buildOffWeekDecisionSet(game.state.lifeBetweenRaces,lifeBetweenRacesContextFromGame(game));}
export function availableTrainingSessions(game){openLifeBetweenRaces(game);return buildTrainingCatalog(game.state.lifeBetweenRaces,lifeBetweenRacesContextFromGame(game)).map(q=>applyTrainingAccessToQuote(q,game.state.lifeBetweenRaces.trainingAccess,{seasonNumber:game.state.seasonNumber,supportDiscount:Number(game.state.trainingSupport?.discount??0),supportSource:game.state.trainingSupport?.source??null}));}
export function trainingSessionQuote(game,id){openLifeBetweenRaces(game);return supportedQuote(game,id);}
function wearGear(game,trainingId){if(trainingId==='conditioning')return[];const gear=game.state.equipmentCareer?.gear;if(!Array.isArray(gear))return[];const used=[];game.state.equipmentCareer.gear=gear.map(item=>{const next=recordEquipmentUse(item,{sessions:1,kind:'practice',conditions:game.state.trainingContext?.conditions??{}});used.push({itemId:next.id,category:next.category,condition:next.condition,quantity:next.quantity});return next;});return used;}
function applyTraining(game,decision,costOverride=null){const cost=costOverride==null?decision.cost:Number(costOverride);if(cost>0&&!game.spend(cost))return{error:'not-enough-money'};for(const [skill,gain]of Object.entries(decision.gains??{}))if(gain)game.skill(skill,gain);game.fatigue(decision.fatigueDelta??0);game.confidence(decision.confidenceDelta??0);let bikeWear=null;if(['starts','motos','coaching','technique','light_ride'].includes(decision.trainingId)){const bike=game.trainBike(),wear=decision.trainingId==='motos'?{condition:-7,parts:{tires:-5,chain:-3,brakes:-2}}:decision.trainingId==='light_ride'||decision.trainingId==='starts'?{condition:-2,parts:{tires:-1,chain:-1}}:{condition:-4,parts:{tires:-3,chain:-2,brakes:-1}};game.wearBike(bike,wear);bikeWear={bikeId:bike?.id??null,...wear};}const gearUse=wearGear(game,decision.trainingId);game.log(`🏋️ ${decision.trainingId.replaceAll('_',' ')}: load ${decision.load}, risk ${decision.risk.band}.`);return{ok:true,bikeWear,gearUse};}
function applyRecovery(game,decision){if(decision.cost>0&&!game.spend(decision.cost))return{error:'not-enough-money'};game.fatigue(decision.fatigueDelta??0);game.stress(decision.stressDelta??0);game.confidence(decision.confidenceDelta??0);if(decision.injuryRecovery>0&&game.rider.injury?.weeksOut>0){game.rider.injury.weeksOut=Math.max(0,game.rider.injury.weeksOut-decision.injuryRecovery);if(game.rider.injury.weeksOut===0)game.rider.injury=null;}return{ok:true};}
export function takeLifeBetweenRacesDecision(game,family,id){openLifeBetweenRaces(game);const ctx=lifeBetweenRacesContextFromGame(game),seed=game.state.seed??game.rng?.seed??1,quote=family==='training'?supportedQuote(game,id):null;if(quote&&!quote.allowed)return{state:game.state.lifeBetweenRaces,decision:null,error:quote.reason,quote};const before=family==='training'?{money:Number(game.family.money??0),week:game.week,seasonNumber:game.state.seasonNumber}:null;let booking=null;if(family==='training'){const b=bookTrainingSession(game.state.lifeBetweenRaces.trainingAccess,quote,{seasonNumber:game.state.seasonNumber,week:game.week});if(b.error)return{error:b.error,quote};game.state.lifeBetweenRaces.trainingAccess=b.state;booking=b.booking;}
 const resolved=family==='training'?resolveTrainingDecision(game.state.lifeBetweenRaces,id,ctx,{seed}):family==='recovery'?resolveRecoveryDecision(game.state.lifeBetweenRaces,id,ctx):{state:game.state.lifeBetweenRaces,decision:null,error:'unknown-family'};if(resolved.error||!resolved.decision)return{...resolved,quote};const applied=family==='training'?applyTraining(game,resolved.decision,quote.cost.outOfPocket):applyRecovery(game,resolved.decision);if(applied.error)return{...resolved,error:applied.error,quote};game.state.lifeBetweenRaces=resolved.state;if(family==='training'){game.state.lifeBetweenRaces.trainingAccess=ensureAccessAfterResolution(game,booking);const usage=trainingUsage(game.state.lifeBetweenRaces,id,{seasonNumber:game.state.seasonNumber}),receipt=createTrainingReceipt({quote,decision:resolved.decision,applied,before,after:{money:Number(game.family.money??0),usage}});receipt.actual.gearUse=applied.gearUse;game.state.lifeBetweenRaces.latestTrainingReceipt=receipt;const row=game.state.lifeBetweenRaces.trainingHistory.at(-1);if(row){row.seasonNumber=game.state.seasonNumber;row.cost=receipt.actual.cost;row.retailCost=quote.cost.retail;row.support=quote.cost.support;row.supportSource=quote.supportSource;row.time=receipt.actual.time;row.receiptId=receipt.id;row.gearUse=applied.gearUse;}return{...resolved,applied,quote,receipt,booking};}return{...resolved,applied};}
function ensureAccessAfterResolution(game,booking){const current=restoreTrainingAccessState(game.state.lifeBetweenRaces.trainingAccess);if(!booking)return current;return consumeTrainingBooking(current,booking.id).state;}
