import { ensureRelationshipLifecycle } from './peopleRelationships2.js';
import { createConflict, repairConflict, evolveGuardianship, classifyEconomicArchetype, seasonAffordability, quoteWork, applyWork } from './peopleEconomyLifePressure.js';
import { createCareerEconomyState } from './careerEconomy2.js';

export function gameEconomicArchetype(game){return classifyEconomicArchetype({age:game.rider?.age,supportLevel:game.family?.support_level,teamBacked:!!game.state?.careerOpportunityState?.team, factory:!!game.state?.careerOpportunityState?.factory,scope:game.state?.careerOpportunityState?.scope??'regional'});}
export function gameSeasonAffordability(game,plannedCost=0){const a=gameEconomicArchetype(game);return seasonAffordability(game.state.careerEconomy,{cash:game.family?.money??0,plannedCost,archetype:a.id});}
export function gameWorkQuote(game,optionId){const slots=Number(game.weekSlots?.().length??0);return quoteWork(optionId,{age:game.rider?.age??18,availableSlots:slots,isRaceWeek:!!game.isRaceWeek?.()});}
export function takeWorkShift(game,optionId){const quote=gameWorkQuote(game,optionId);if(!quote.allowed)return{error:quote.reason,quote};const opening=Number(game.family?.money??0);const resolved=applyWork(game.state.careerEconomy,optionId,{age:game.rider?.age??18,availableSlots:quote.availableSlots,isRaceWeek:!!game.isRaceWeek?.(),seasonNumber:game.state.seasonNumber,week:game.week,openingBalance:game.state.careerEconomy?.openingBalance??opening});game.state.careerEconomy=resolved.economy;if(!resolved.duplicate){game.addMoney?.(resolved.income);game.fatigue?.(resolved.fatigueDelta);game.state.workHistory??=[];game.state.workHistory.push({sourceId:resolved.entry.sourceId,seasonNumber:game.state.seasonNumber,week:game.week,optionId,income:resolved.income,timeUsed:resolved.timeUsed});}return{...resolved,quote};}
export function startRelationshipConflict(game,personId,input={}){const raw=game.state.relationships?.[personId];if(!raw)return{error:'unknown-person'};const next=createConflict(raw,{...input,seasonNumber:game.state.seasonNumber,week:game.week});game.state.relationships[personId]=next;game.relationships?._cache?.delete(personId);return{relationship:next};}
export function repairRelationshipConflict(game,personId,input={}){const raw=game.state.relationships?.[personId];if(!raw)return{error:'unknown-person'};const next=repairConflict(raw,{...input,seasonNumber:game.state.seasonNumber,week:game.week});game.state.relationships[personId]=next;game.relationships?._cache?.delete(personId);return{relationship:next};}
export function refreshGuardianRoles(game,responsibility=50){for(const [id,raw] of Object.entries(game.state.relationships??{})){const rec=ensureRelationshipLifecycle(raw);if(rec.lifecycle.role==='Parent'||['Parent Advisor','Advisor'].includes(rec.lifecycle.role))game.state.relationships[id]=evolveGuardianship(rec,{age:game.rider?.age??12,responsibility,seasonNumber:game.state.seasonNumber,week:game.week});}game.relationships?._cache?.clear();return game.state.relationships;}
export function ensureEconomyForGame(game){game.state.careerEconomy=createCareerEconomyState(game.state.careerEconomy,game.family?.money??0);return game.state.careerEconomy;}
