import { restoreLifeBetweenRacesState } from './lifeBetweenRaces.js';

export const TRAINING_ACCESS_VERSION=1;
export function createTrainingAccessState(){return{version:1,resources:[],bookings:[],consumptions:[]};}
export function restoreTrainingAccessState(raw){const b=createTrainingAccessState();if(!raw||typeof raw!=='object')return b;return{...b,...raw,resources:Array.isArray(raw.resources)?raw.resources:[],bookings:Array.isArray(raw.bookings)?raw.bookings:[],consumptions:Array.isArray(raw.consumptions)?raw.consumptions:[]};}
export function addTrainingResource(state,input={}){const next=restoreTrainingAccessState(state),id=input.id??`training-resource-${next.resources.length+1}`;next.resources.push({id,type:input.type??'pass',trainingIds:[...(input.trainingIds??[])],quantity:Math.max(0,Number(input.quantity??1)),source:input.source??'family-paid',retailValue:Math.max(0,Number(input.retailValue??0)),expiresSeason:input.expiresSeason??null,label:input.label??'Training access'});return next;}
export function eligibleTrainingResource(state,trainingId,{seasonNumber=1}={}){return restoreTrainingAccessState(state).resources.find(r=>r.quantity>0&&(r.trainingIds.length===0||r.trainingIds.includes(trainingId))&&(r.expiresSeason==null||Number(r.expiresSeason)>=Number(seasonNumber)))??null;}
export function applyTrainingAccessToQuote(quote,accessState,{seasonNumber=1,supportDiscount=0,supportSource=null}={}){if(!quote)return quote;const resource=eligibleTrainingResource(accessState,quote.trainingId,{seasonNumber}),retail=Number(quote.cost?.retail??0);let support=0,source=null;if(resource){support=retail;source=resource.source;}else if(supportDiscount>0){support=Math.min(retail,Math.round(retail*Math.max(0,Math.min(1,Number(supportDiscount)))));source=supportSource??'support';}return{...quote,cost:{retail,support,outOfPocket:Math.max(0,retail-support)},access:resource?{resourceId:resource.id,label:resource.label,type:resource.type,remaining:resource.quantity,source:resource.source,expiresSeason:resource.expiresSeason}:null,supportSource:source};}
export function bookTrainingSession(state,quote,{seasonNumber=1,week=1}={}){const next=restoreTrainingAccessState(state);if(!quote?.allowed)return{state:next,error:quote?.reason??'session-unavailable',booking:null};const booking={id:`training-booking-${next.bookings.length+1}`,trainingId:quote.trainingId,seasonNumber,week,status:'reserved',retail:Number(quote.cost.retail??0),outOfPocket:Number(quote.cost.outOfPocket??0),resourceId:quote.access?.resourceId??null,supportSource:quote.supportSource??null};next.bookings.push(booking);return{state:next,error:null,booking};}
export function cancelTrainingBooking(state,bookingId){const next=restoreTrainingAccessState(state),b=next.bookings.find(x=>x.id===bookingId);if(!b||b.status!=='reserved')return{state:next,error:'booking-not-cancellable'};b.status='cancelled';return{state:next,error:null,booking:b,refund:b.outOfPocket};}
export function consumeTrainingBooking(state,bookingId){const next=restoreTrainingAccessState(state),b=next.bookings.find(x=>x.id===bookingId);if(!b||b.status!=='reserved')return{state:next,error:'booking-not-consumable'};if(b.resourceId){const r=next.resources.find(x=>x.id===b.resourceId);if(!r||r.quantity<=0)return{state:next,error:'access-exhausted'};r.quantity-=1;next.consumptions.push({bookingId,resourceId:r.id,trainingId:b.trainingId});}b.status='consumed';return{state:next,error:null,booking:b};}
export function trainingAccessSummary(state){const s=restoreTrainingAccessState(state);return{resources:s.resources.filter(r=>r.quantity>0),reserved:s.bookings.filter(b=>b.status==='reserved'),used:s.consumptions.length};}
