import { SIM_DEPTHS } from './game.js';
import { createFamilyLifeBuilderState, householdTemplate } from './systems/familyLifeBuilder.js';
import { createRacingSupportHomeState } from './systems/familyRacingSupportHome.js';
import { buildFamilyStory, initializeFamilyLife, migrateFamilyLifeSave } from './systems/familyLifeExperience.js';

const STEPS=['background','family-motocross','family-household','family-school','family-support','family-home','family-review'];
const FINANCES=[['tight','Tight','Racing takes sacrifice. Used equipment and careful choices are part of the journey.'],['comfortable','Comfortable','There is room for racing, but bigger trips and new bikes still require choices.'],['well_off','Well-off','Your family can invest in racing, though expectations and major commitments still matter.'],['wealthy','Wealthy','Money removes many barriers, but pressure and expectations can grow.']];
const KNOWLEDGE=[['new','New to the sport','Your family is learning motocross with you.'],['weekend','Weekend racing family','Your family understands local racing and the basics.'],['motocross_family','Motocross family','Racing has already been part of family life for years.'],['industry','Industry family','A parent or guardian has deep racing, mechanical, dealership, coaching, or industry knowledge.']];
const HOUSEHOLDS=[['two_parent','Two-parent household','Two guardians share family life and can divide racing responsibilities.'],['single_parent','Single-parent household','One parent carries most family and racing responsibilities.'],['split_household','Split / co-parenting household','Racing and school responsibilities move across two homes.'],['guardian_household','Grandparent / guardian household','A guardian or grandparent is the central adult in the rider’s life.']];
const SCHOOLS=[['public','Public school','Traditional weekday schedule with real travel and absence pressure.'],['private','Private school','Structured school schedule with added family cost pressure.'],['homeschool','Homeschool','More weekday flexibility, but schoolwork still has to get done.'],['online','Online / flexible school','School can travel with you, but workload and deadlines remain.']];
const SUPPORT=[['family_diy','We do everything ourselves','Family labor keeps costs down but consumes evenings and weekends.'],['guardian_mechanic','Parent / guardian is the mechanic','A guardian takes primary responsibility for keeping the bike ready.'],['local_shop','Local shop helps us','A recurring shop relationship adds capability at a real cost.'],['professional','We pay for professional help','Professional support reduces family labor but raises program cost.'],['hybrid','Hybrid support','Family and outside help share the work.']];
const HOMES=[['minimal','Small home / minimal storage','Bikes and gear compete for space. Expansion will require creativity or a move.'],['basic','Typical home + basic garage','Enough room to start, but storage and workshop space are limited.'],['workshop','Home with usable workshop','Real work space and tools make running the program easier.'],['rural','Rural property with room to grow','Space to ride and expand, balanced by upkeep and property demands.']];

function el(tag,attrs={},...kids){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k.startsWith('on')&&typeof v==='function')n.addEventListener(k.slice(2).toLowerCase(),v);else if(v!=null)n.setAttribute(k,v);}for(const kid of kids.flat()){if(kid==null)continue;n.appendChild(typeof kid==='string'?document.createTextNode(kid):kid);}return n;}
function ensureStyle(){if(document.getElementById('family-life-builder-style'))return;const s=document.createElement('style');s.id='family-life-builder-style';s.textContent=`.family-builder{max-width:680px;margin:0 auto;padding:0 12px 28px}.family-progress{height:6px;background:rgba(255,255,255,.1);border-radius:99px;overflow:hidden;margin:10px 0 18px}.family-progress>i{display:block;height:100%;background:currentColor}.family-choice{display:block;width:100%;text-align:left;padding:15px;margin:10px 0;border-radius:14px;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.04);color:inherit}.family-choice.sel{outline:2px solid currentColor;background:rgba(255,255,255,.09)}.family-choice b{display:block;margin-bottom:5px}.family-choice span{opacity:.72;line-height:1.35}.family-story{padding:18px;border-radius:16px;background:rgba(255,255,255,.06);margin:12px 0}.family-tags{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0 14px}.family-tag{font-size:12px;padding:5px 8px;border-radius:99px;background:rgba(255,255,255,.09)}.family-two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.family-list{padding-left:18px}.family-actions{display:flex;justify-content:space-between;gap:10px;margin-top:18px}.family-actions .btn{min-height:44px}.family-guardian{padding:12px;border:1px solid rgba(255,255,255,.12);border-radius:12px;margin-top:10px}.family-guardian input{width:100%;margin-top:6px}@media(max-width:520px){.family-two{grid-template-columns:1fr}.family-builder{width:100%;box-sizing:border-box}.family-choice{box-sizing:border-box}.family-actions{position:sticky;bottom:0;padding:10px 0;background:linear-gradient(transparent,rgba(10,10,12,.96) 35%)}}`;document.head.appendChild(s);}
function selection(o){o.familyBuilder=createFamilyLifeBuilderState(o.familyBuilder??{});o.racingSupportHome=createRacingSupportHomeState(o.racingSupportHome??{});return o;}
function optionButton(label,desc,selected,onClick){return el('button',{class:'family-choice'+(selected?' sel':''),onclick:onClick},el('b',{},label),el('span',{},desc));}
function progress(step){const i=Math.max(0,STEPS.indexOf(step));return el('div',{class:'family-progress','aria-label':`Family builder step ${i+1} of ${STEPS.length}`},el('i',{style:`width:${((i+1)/STEPS.length)*100}%`}));}
function header(step,title,body){const i=Math.max(0,STEPS.indexOf(step));return [el('div',{class:'eyebrow'},`Build Your Family Life · ${i+1} of ${STEPS.length}`),progress(step),el('h2',{},title),el('p',{class:'small faint'},body)];}
function nav(app,o,back,next,nextText='Next ›'){return el('div',{class:'family-actions'},el('button',{class:'btn ghost',onclick:()=>{o.step=back;app.renderTitle();}},'‹ Back'),el('button',{class:'btn primary',onclick:()=>{o.step=next;app.renderTitle();}},nextText));}

function renderFamilyStep(app,o){selection(o);ensureStyle();const b=o.familyBuilder,s=o.racingSupportHome;let body=[];
  if(o.step==='background'){body=[...header(o.step,'Where does your family stand financially?','This sets the starting pressure around racing. It is a circumstance, not a difficulty setting.'),...FINANCES.map(([id,l,d])=>optionButton(l,d,b.financial===id,()=>{b.financial=id;o.step='family-motocross';app.renderTitle();})),nav(app,o,'identity','family-motocross')];}
  else if(o.step==='family-motocross'){body=[...header(o.step,'What does your family know about motocross?','Money and motocross knowledge are separate parts of your story.'),...KNOWLEDGE.map(([id,l,d])=>optionButton(l,d,b.motocrossKnowledge===id,()=>{b.motocrossKnowledge=id;o.step='family-household';app.renderTitle();})),nav(app,o,'background','family-household')];}
  else if(o.step==='family-household'){const guards=b.guardians.length?b.guardians:householdTemplate(b.household);body=[...header(o.step,'Who is home with you?','Household structure determines who shares the work, support, travel, and sacrifice.'),...HOUSEHOLDS.map(([id,l,d])=>optionButton(l,d,b.household===id,()=>{b.household=id;b.guardians=householdTemplate(id);app.renderTitle();})),...guards.map((g,idx)=>el('div',{class:'family-guardian'},el('b',{},g.relation),el('label',{class:'small faint'},'Name'),el('input',{value:g.name,oninput:e=>{b.guardians=guards;b.guardians[idx].name=e.target.value||g.relation;}}))),nav(app,o,'family-motocross','family-school')];}
  else if(o.step==='family-school'){body=[...header(o.step,'What is school life like?','School changes time, travel flexibility, and responsibilities—not rider speed.'),...SCHOOLS.map(([id,l,d])=>optionButton(l,d,b.school===id,()=>{b.school=id;o.step='family-support';app.renderTitle();})),nav(app,o,'family-household','family-support')];}
  else if(o.step==='family-support'){body=[...header(o.step,'How does the family support racing?','Decide who carries the wrenching and race-program burden.'),...SUPPORT.map(([id,l,d])=>optionButton(l,d,s.supportModel===id,()=>{s.supportModel=id;o.step='family-home';app.renderTitle();})),nav(app,o,'family-school','family-home')];}
  else if(o.step==='family-home'){body=[...header(o.step,'Where does the program live?','Your starting home controls storage, workspace, transport friction, and future compound possibilities.'),...HOMES.map(([id,l,d])=>optionButton(l,d,s.home===id,()=>{s.home=id;o.step='family-review';app.renderTitle();})),nav(app,o,'family-support','family-review','Review My Story ›')];}
  else if(o.step==='family-review'){const story=buildFamilyStory(b,s);body=[...header(o.step,'Your Story','These are starting circumstances. Your family, finances, school, support, and home can all change over time.'),el('div',{class:'family-story','data-testid':'family-story'},el('h2',{},story.title),el('div',{class:'family-tags'},...story.details.map(x=>el('span',{class:'family-tag'},x))),el('p',{},story.narrative),el('p',{},el('b',{},'Home: '),story.home),el('p',{},el('b',{},'Racing support: '),story.support),el('p',{},el('b',{},'Starting equipment: '),story.startingEquipment),el('div',{class:'family-two'},el('div',{},el('b',{},'Starting strengths'),el('ul',{class:'family-list'},...(story.strengths.length?story.strengths:['A family willing to begin']).map(x=>el('li',{},x))),el('div',{},el('b',{},'Starting pressures'),el('ul',{class:'family-list'},...(story.pressures.length?story.pressures:['Learning what racing asks of the family']).map(x=>el('li',{},x))))),el('p',{class:'small faint'},'No family choice grants rider speed or talent.')),nav(app,o,'family-home','options','Looks Good ›')];}
  else if(o.step==='options'){body=[el('div',{class:'eyebrow'},'Final step'),el('h2',{},'How do you want to play?'),el('p',{class:'small faint'},'Simulation depth changes how often the game pauses for decisions. Your family story stays the same.'),...Object.values(SIM_DEPTHS).map(d=>optionButton(d.label,d.blurb,o.depth===d.key,()=>{o.depth=d.key;app.renderTitle();})),el('div',{class:'family-actions'},el('button',{class:'btn ghost',onclick:()=>{o.step='family-review';app.renderTitle();}},'‹ Back'),el('button',{class:'btn primary','data-testid':'family-begin-career',onclick:()=>app.startGame({...o})},'Begin Career →'))];}
  const view=el('div',{},el('div',{class:'title-wrap'},el('div',{class:'logo-mark'},'🏍️'),el('h1',{},'Legacy: Motocross'),el('div',{class:'tagline'},'Create a life worth remembering.')),el('div',{class:'card family-builder','data-testid':'family-life-builder'},...body),el('p',{class:'faint small center'},'Your circumstances can evolve. Your story is not a class.'));
  app.root.replaceChildren(view);window.scrollTo(0,0);
}

export function installFamilyLifeBuilderUiPatch(App){
  const originalRenderTitle=App.prototype.renderTitle;
  App.prototype.renderTitle=function familyLifeTitle(...args){
    if(this.onboard&&[...STEPS,'options'].includes(this.onboard.step))return renderFamilyStep(this,this.onboard);
    return originalRenderTitle.apply(this,args);
  };
  const originalStart=App.prototype.startGame;
  App.prototype.startGame=function familyLifeStart(o){
    selection(o);const legacyBackground=o.familyBuilder.financial==='wealthy'?'rich':o.familyBuilder.school==='homeschool'?'homeschool':o.familyBuilder.motocrossKnowledge==='new'?'clueless':o.familyBuilder.motocrossKnowledge==='industry'?'blue_collar':'working_class';
    originalStart.call(this,{...o,background:legacyBackground});
    initializeFamilyLife(this.game,o.familyBuilder,o.racingSupportHome);this.saveGame();this.render?.();
  };
  const originalLoad=App.prototype.loadSave;
  App.prototype.loadSave=function familyLifeLoad(){const save=originalLoad.call(this);return save?migrateFamilyLifeSave(save):save;};
}
