import { createCareerOpportunityState, careerOpportunitySummary, evaluateOpportunity, decideCareerOpportunity } from './systems/careerOpportunities2.js';
const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function gameOf(app){return app.game??app;}
function ensure(game){game.state.careerOpportunities2=createCareerOpportunityState(game.state.careerOpportunities2);return game.state.careerOpportunities2;}
function context(game){return game.opportunity?.context?.()??{week:game.week,seasonNumber:game.state.seasonNumber,rider:game.rider,family:game.family,guardianApproved:Number(game.rider?.age??18)>=18};}
function html(app){const g=gameOf(app),s=ensure(g),summary=careerOpportunitySummary(s),o=s.active[0];const history=summary.recent.map(x=>`<li><strong>${esc(x.title)}</strong> — ${esc(x.status)}</li>`).join('');if(!o)return `<section class="card ui2-career-opportunities" data-testid="career-opportunity-history"><div class="eyebrow">CAREER OPPORTUNITIES</div><h3>No major offer on the table right now.</h3><p class="small muted">Results, relationships, timing and the world around you determine what comes next.</p>${history?`<ul>${history}</ul>`:''}</section>`;const e=evaluateOpportunity(s,o.id,context(g));const terms=Object.entries(o.terms??{}).slice(0,5).map(([k,v])=>`<li><strong>${esc(k.replaceAll('_',' '))}</strong>: ${esc(Array.isArray(v)?v.join(', '):v)}</li>`).join('');const obligations=(o.obligations??[]).map(x=>`<li>${esc(x)}</li>`).join('');const impacts=Object.entries(o.familyImpact??{}).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join(' · ')||'Manageable';return `<section class="card ui2-career-opportunities" data-testid="career-opportunity-scene" data-opportunity-id="${esc(o.id)}"><div class="eyebrow">A DOOR OPENED</div><h2>${esc(o.title)}</h2><p class="small faint">${esc(o.source)} · expires after week ${o.expiresWeek}</p><div class="career-opportunity-grid"><div><strong>What you get</strong><ul>${terms}</ul></div><div><strong>What they expect</strong><ul>${obligations||'<li>No special obligations</li>'}</ul></div></div><p><strong>Family impact:</strong> ${impacts}</p><p><strong>Upside ${o.value}/100 · Risk ${o.risk}/100</strong>${o.guardianRequired?' · Parent/guardian approval required':''}</p><p class="small muted">Decision read: ${esc(e?.recommendation??'consider')}</p><div class="career-opportunity-actions toolbar"><button class="btn ghost" type="button" data-career-decision="decline">Decline</button><button class="btn" type="button" data-career-decision="counter">Counter</button><button class="btn primary" type="button" data-career-decision="accept">Accept Opportunity</button></div>${history?`<details><summary>Opportunity history</summary><ul>${history}</ul></details>`:''}</section>`;}
function node(app){const t=document.createElement('template');t.innerHTML=html(app).trim();return t.content.firstElementChild;}
function wire(app,host){host.querySelectorAll('[data-career-decision]').forEach(btn=>btn.addEventListener('click',()=>{const g=gameOf(app),s=ensure(g),o=s.active[0];if(!o)return;const decision=btn.dataset.careerDecision,ctx=context(g);const result=decideCareerOpportunity(s,o.id,decision,{...ctx,guardianApproved:Number(g.rider?.age??18)>=18||g.isParent===true});if(result.error){g.addNews?.(`Opportunity decision blocked: ${result.error}`,'opportunity');return;}g.state.careerOpportunities2=result.state;if(result.opportunity.status==='accepted'){const cost=Number(result.opportunity.terms?.cost??0);if(cost>0&&g.family.money>=cost)g.family.money-=cost;g.addNews?.(`Accepted: ${result.opportunity.title}`,'opportunity');}else g.addNews?.(`${result.opportunity.status}: ${result.opportunity.title}`,'opportunity');app.saveGame?.();app.render?.();}));}
export function installUi2CareerOpportunitiesPatch(App){if(!App?.prototype||App.prototype.__careerOpportunities2Installed)return;App.prototype.__careerOpportunities2Installed=true;if(typeof App.prototype.renderStatsTab==='function'){const original=App.prototype.renderStatsTab;App.prototype.renderStatsTab=function(...args){const out=original.apply(this,args);const card=node(this);out.appendChild(card);wire(this,card);return out;};}}
