import { peopleStory, personStory, fundingStory } from './systems/peopleEconomyPresentation.js';
import { repairConflict } from './systems/peopleEconomyLifePressure.js';
import { recordBondInteraction } from './systems/peopleEconomyBondsRisk.js';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dollars=v=>`$${Math.round(Math.max(0,Number(v)||0)).toLocaleString()}`;
function ensureStyles(){if(document.querySelector('link[data-ui2-people-economy]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./ui2PeopleEconomy.css';l.dataset.ui2PeopleEconomy='1';document.head.appendChild(l);}
function gameOf(app){return app.game??app;}
function economyContext(g){const fp=g.state?.financialPosture??{},planned=Number(g.state?.seasonPlan?.forecast?.total??g.state?.seasonLifecycle?.opening?.brief?.money?.seasonCost??0);return{cash:Number(g.family?.money??0),seasonNumber:g.state?.seasonNumber??1,plannedCost:planned,debtExposure:Number(fp.debtExposure??0),monthlyLivingCost:Number(fp.monthlyLivingCost??800),equipmentRisk:Number(fp.equipmentRisk??0),familyStrain:Number(fp.familyStrain??g.family?.stress??0),commitmentRisk:Number(fp.commitmentRisk??0),archetype:fp.archetype??'budget_amateur',supportExpected:Number(fp.supportExpected??0)};}
function relationshipCard(app){const g=gameOf(app),story=peopleStory(g.state.relationships,g.state.people2);if(!story.people.length)return null;const selectedId=app._people2SelectedId&&g.state.relationships[app._people2SelectedId]?app._people2SelectedId:story.people[0].id;app._people2SelectedId=selectedId;const p=personStory(g.state.relationships[selectedId],g.state.people2),tabs=story.people.map(x=>`<button type="button" class="pe2-person-chip${x.id===selectedId?' active':''}" data-person-id="${esc(x.id)}"><strong>${esc(x.name)}</strong><span>${esc(x.role)} · ${esc(x.state)}</span></button>`).join('');const timeline=[...p.recentSupport.map(x=>({...x,type:'Help'})),...p.recentHistory.map(x=>({...x,type:'Moment'}))].slice(0,5).map(x=>`<li><small>${esc(x.when)} · ${esc(x.type)}</small><strong>${esc(x.label)}</strong>${x.detail?`<span>${esc(x.detail)}</span>`:''}</li>`).join('')||'<li><span>No major shared moments recorded yet.</span></li>';const actions=p.conversation.map(a=>`<button class="btn${a==='follow_through'?' primary':''}" type="button" data-people-action="${esc(a)}">${esc(a==='follow_through'?'Follow Through':a==='check_in'?'Check In':a[0].toUpperCase()+a.slice(1))}</button>`).join('');return `<section class="card pe2-card" data-testid="people-relationship-story"><div class="eyebrow">PEOPLE</div><h2>${esc(story.headline)}</h2><div class="pe2-person-strip">${tabs}</div><article class="pe2-person-focus" data-testid="people-focus-${esc(p.id)}"><div class="pe2-focus-head"><div><small>${esc(p.role)} · ${esc(p.state)}</small><h3>${esc(p.name)}</h3></div>${p.tension?'<span class="pe2-status warn">Needs attention</span>':'<span class="pe2-status">Current relationship</span>'}</div><p>${esc(p.headline)}</p>${p.supportLine?`<p class="small muted">${esc(p.supportLine)}</p>`:''}<div class="pe2-readable"><span>Trust <strong>${p.dimensions.trust}</strong></span><span>Closeness <strong>${p.dimensions.closeness}</strong></span><span>Respect <strong>${p.dimensions.respect}</strong></span>${p.dimensions.conflict>=40?`<span>Tension <strong>${p.dimensions.conflict}</strong></span>`:''}</div><div class="pe2-conversation"><small>WHAT DO YOU DO?</small><div class="toolbar">${actions}</div></div><details><summary>Shared history</summary><ul class="pe2-timeline">${timeline}</ul></details></article></section>`;}
function economyCard(app){const g=gameOf(app),f=fundingStory(g.state.careerEconomy,economyContext(g));const cats=f.categories.map(x=>`<li><span>${esc(x.name)}</span><strong>${dollars(x.value)}</strong></li>`).join('')||'<li><span>No major costs recorded yet.</span></li>';const sources=f.sources.map(x=>`<li><span>${esc(x.name)}</span><strong>${dollars(x.value)}</strong></li>`).join('')||'<li><span>Funding sources will appear as the season develops.</span></li>';const recent=f.recent.map(x=>`<li><span>${esc(x.label)}<small>${esc(x.source)}${x.support?` · ${dollars(x.support)} support`:''}</small></span><strong>${x.status==='in'?'+':'-'}${dollars(Math.abs(x.amount))}</strong></li>`).join('');return `<section class="card pe2-card" data-testid="career-economy-story"><div class="eyebrow">PROGRAM MONEY</div><div class="pe2-focus-head"><div><small>${esc(f.posture.band.toUpperCase())} · ${f.posture.pressureScore}/100 pressure</small><h2>${esc(f.headline)}</h2></div><span class="pe2-status ${f.posture.band==='critical'||f.posture.band==='strained'?'warn':''}">${esc(f.capacity.replaceAll('-',' '))}</span></div><p>${esc(f.fundingLine)}</p><div class="pe2-money-grid"><div><small>OUT OF POCKET</small><strong>${dollars(f.outOfPocket)}</strong></div><div><small>SUPPORT COVERED</small><strong>${dollars(f.support)}</strong></div><div><small>CASH FLOW IN</small><strong>${dollars(f.summary.cashIn)}</strong></div><div><small>CUSHION</small><strong>${f.posture.cushionMonths} mo</strong></div></div>${f.posture.drivers.length?`<p class="small muted"><strong>What is creating pressure:</strong> ${esc(f.posture.drivers.join(' · '))}</p>`:''}<div class="pe2-split"><div><h3>Where it’s going</h3><ul class="pe2-money-list">${cats}</ul></div><div><h3>Who is carrying it</h3><ul class="pe2-money-list">${sources}</ul></div></div>${recent?`<details><summary>Recent money story</summary><ul class="pe2-money-list">${recent}</ul></details>`:''}</section>`;}
function node(html){const t=document.createElement('template');t.innerHTML=html.trim();return t.content.firstElementChild;}
function wirePeople(app,host){host.querySelectorAll('[data-person-id]').forEach(b=>b.addEventListener('click',()=>{app._people2SelectedId=b.dataset.personId;app.render();}));host.querySelectorAll('[data-people-action]').forEach(b=>b.addEventListener('click',()=>{const g=gameOf(app),id=app._people2SelectedId,raw=g.state.relationships?.[id];if(!raw)return;const action=b.dataset.peopleAction;if(action==='check_in')g.state.relationships[id]=recordBondInteraction(raw,{kind:'conversation',intensity:2,seasonNumber:g.state.seasonNumber,week:g.week});else g.state.relationships[id]=repairConflict(raw,{action,seasonNumber:g.state.seasonNumber,week:g.week});g.relationships?._cache?.delete?.(id);app.saveGame?.();app.render();}));}
export function installUi2PeopleEconomyPatch(App){if(!App?.prototype||App.prototype.__ui2PeopleEconomyInstalled)return;App.prototype.__ui2PeopleEconomyInstalled=true;ensureStyles();if(typeof App.prototype.renderStatsTab==='function'){const prior=App.prototype.renderStatsTab;App.prototype.renderStatsTab=function(...args){const out=prior.apply(this,args),people=relationshipCard(this),economy=economyCard(this);if(people){const n=node(people);out.appendChild(n);wirePeople(this,n);}if(economy)out.appendChild(node(economy));return out;};}}
